### ISSUE TITLE
Deploy on Maven Central public

### ISSUE THREAD

**Issue by oomelianchuk** [Xceptance/neodymium-plugin-xcmailr#6]

**Comment by oomelianchuk** [comment]
Released via Jenkins. To fix deployment via Github ask @jowerner for the new gpg-key (and probably for new gpg-passphrase)

**Comment by occupant23** [comment]
Place of deployment needs to be discussed: Currently Jenkins until further notice.

**Comment by occupant23** [comment]
If we need differences for the release branch this could be an approach: https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
