### ISSUE TITLE
Update plugin documentation 

### ISSUE THREAD

**Issue by oomelianchuk** [Xceptance/neodymium-plugin-xcmailr#9]
As the Neodymium-XcMailr-Plugin supports new features, these should be described in the neodymium library

**Comment by occupant23** [comment]
Update done @oomelianchuk Please review the documentation. and close the issue when everything is fine.

**Comment by occupant23** [comment]
Documentation can be found here: https://github.com/Xceptance/neodymium-library/wiki/Xcmailr-Plugin
